CREATE TABLE `nutrition_principals` (`id` text PRIMARY KEY NOT NULL,`credential_hash` text NOT NULL,`access_version` integer DEFAULT 1 NOT NULL CHECK (`access_version` > 0),`archived_at` integer,`last_authenticated_at` integer,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);
--> statement-breakpoint
CREATE TABLE `nutrition_profiles` (`id` text PRIMARY KEY NOT NULL,`owner_principal_id` text NOT NULL,`linked_household_profile_id` text,`display_name` text NOT NULL,`avatar_url` text DEFAULT '' NOT NULL,`profile_type` text NOT NULL CHECK (`profile_type` IN ('adult','dependent','guest','unassigned')),`date_of_birth` text,`height_centimeters` real CHECK (`height_centimeters` IS NULL OR `height_centimeters` > 0),`current_weight_kilograms` real CHECK (`current_weight_kilograms` IS NULL OR `current_weight_kilograms` > 0),`measurement_system` text NOT NULL CHECK (`measurement_system` IN ('metric','imperial')),`reference_sex_category` text CHECK (`reference_sex_category` IS NULL OR `reference_sex_category` IN ('female','male')),`activity_level` text,`nutrition_goal_type` text NOT NULL,`target_weight_kilograms` real,`target_date` text,`explicitly_entered_life_stage` text,`dietary_preferences` text DEFAULT '[]' NOT NULL,`food_allergies` text DEFAULT '[]' NOT NULL,`dietary_exclusions` text DEFAULT '[]' NOT NULL,`estimated_targets_enabled` integer DEFAULT false NOT NULL CHECK (`estimated_targets_enabled` IN (0,1)),`estimated_target_consent` integer DEFAULT false NOT NULL CHECK (`estimated_target_consent` IN (0,1)),`weight_tracking_enabled` integer DEFAULT false NOT NULL CHECK (`weight_tracking_enabled` IN (0,1)),`comparison_visibility` text NOT NULL,`diary_visibility` text NOT NULL,`preferred_energy_unit` text NOT NULL,`daily_reset_timezone` text NOT NULL,`week_starts_on` integer NOT NULL CHECK (`week_starts_on` BETWEEN 0 AND 6),`reference_jurisdiction` text NOT NULL,`version` integer DEFAULT 1 NOT NULL CHECK (`version` > 0),`archived_at` integer,`created_at` integer NOT NULL,`updated_at` integer NOT NULL,FOREIGN KEY (`owner_principal_id`) REFERENCES `nutrition_principals`(`id`) ON DELETE restrict,FOREIGN KEY (`linked_household_profile_id`) REFERENCES `profiles`(`id`) ON DELETE set null);
--> statement-breakpoint
CREATE INDEX `nutrition_profiles_owner_idx` ON `nutrition_profiles` (`owner_principal_id`);
--> statement-breakpoint
CREATE INDEX `nutrition_profiles_household_link_idx` ON `nutrition_profiles` (`linked_household_profile_id`);
--> statement-breakpoint
CREATE TABLE `nutrition_permission_versions` (`id` text PRIMARY KEY NOT NULL,`nutrition_profile_id` text NOT NULL,`principal_id` text NOT NULL,`revision` integer NOT NULL CHECK (`revision` > 0),`state` text NOT NULL CHECK (`state` IN ('granted','revoked')),`role` text NOT NULL CHECK (`role` IN ('guardian','viewer')),`can_view_diary` integer NOT NULL,`can_view_measurements` integer NOT NULL,`can_manage_profile` integer NOT NULL,`can_manage_goals` integer NOT NULL,`can_view_comparison` integer NOT NULL,`can_export_data` integer NOT NULL,`can_delete_data` integer NOT NULL,`expires_at` integer,`supersedes_permission_id` text,`created_by_principal_id` text NOT NULL,`created_at` integer NOT NULL,FOREIGN KEY (`nutrition_profile_id`) REFERENCES `nutrition_profiles`(`id`) ON DELETE restrict,FOREIGN KEY (`principal_id`) REFERENCES `nutrition_principals`(`id`) ON DELETE restrict,FOREIGN KEY (`supersedes_permission_id`) REFERENCES `nutrition_permission_versions`(`id`) ON DELETE restrict,FOREIGN KEY (`created_by_principal_id`) REFERENCES `nutrition_principals`(`id`) ON DELETE restrict);
--> statement-breakpoint
CREATE UNIQUE INDEX `nutrition_permission_revision_idx` ON `nutrition_permission_versions` (`nutrition_profile_id`,`principal_id`,`revision`);
--> statement-breakpoint
CREATE INDEX `nutrition_permission_profile_idx` ON `nutrition_permission_versions` (`nutrition_profile_id`);
--> statement-breakpoint
CREATE TABLE `nutrition_goal_versions` (`id` text PRIMARY KEY NOT NULL,`nutrition_profile_id` text NOT NULL,`series_id` text NOT NULL,`revision` integer NOT NULL CHECK (`revision` > 0),`nutrient_code` text NOT NULL,`unit` text NOT NULL,`source_type` text NOT NULL,`source_reference_id` text,`starts_on` text NOT NULL,`ends_on` text,`state` text NOT NULL,`kind` text NOT NULL,`value` real,`minimum` real,`maximum` real,`note` text DEFAULT '' NOT NULL,`supersedes_goal_version_id` text,`created_by_principal_id` text NOT NULL,`created_at` integer NOT NULL,FOREIGN KEY (`nutrition_profile_id`) REFERENCES `nutrition_profiles`(`id`) ON DELETE restrict,FOREIGN KEY (`nutrient_code`) REFERENCES `nutrient_definitions`(`code`) ON DELETE restrict,FOREIGN KEY (`supersedes_goal_version_id`) REFERENCES `nutrition_goal_versions`(`id`) ON DELETE restrict,FOREIGN KEY (`created_by_principal_id`) REFERENCES `nutrition_principals`(`id`) ON DELETE restrict,CHECK ((`kind` IN ('target','minimum') AND `value` > 0 AND `minimum` IS NULL AND `maximum` IS NULL) OR (`kind`='range' AND `value` IS NULL AND `minimum` > 0 AND `maximum` >= `minimum`) OR (`kind`='limit' AND `value` IS NULL AND `minimum` IS NULL AND `maximum` > 0)));
--> statement-breakpoint
CREATE UNIQUE INDEX `nutrition_goal_series_revision_idx` ON `nutrition_goal_versions` (`series_id`,`revision`);
--> statement-breakpoint
CREATE INDEX `nutrition_goal_profile_idx` ON `nutrition_goal_versions` (`nutrition_profile_id`);
--> statement-breakpoint
CREATE TABLE `nutrition_body_measurements` (`id` text PRIMARY KEY NOT NULL,`nutrition_profile_id` text NOT NULL,`measured_at` integer NOT NULL,`weight_kilograms` real NOT NULL CHECK (`weight_kilograms` > 0),`source_type` text NOT NULL CHECK (`source_type` IN ('manual','imported')),`approximate` integer NOT NULL CHECK (`approximate` IN (0,1)),`note` text DEFAULT '' NOT NULL,`created_by_principal_id` text NOT NULL,`created_at` integer NOT NULL,FOREIGN KEY (`nutrition_profile_id`) REFERENCES `nutrition_profiles`(`id`) ON DELETE restrict,FOREIGN KEY (`created_by_principal_id`) REFERENCES `nutrition_principals`(`id`) ON DELETE restrict);
--> statement-breakpoint
CREATE INDEX `nutrition_measurement_profile_time_idx` ON `nutrition_body_measurements` (`nutrition_profile_id`,`measured_at`);
