CREATE TABLE `nutrition_intake_revisions` (`id` text PRIMARY KEY NOT NULL,`series_id` text NOT NULL,`revision` integer NOT NULL CHECK (`revision` > 0),`nutrition_profile_id` text NOT NULL,`occurred_at` integer NOT NULL,`meal_slot` text NOT NULL CHECK (`meal_slot` IN ('breakfast','lunch','dinner','snack','other')),`state` text NOT NULL CHECK (`state` IN ('eaten','skipped','corrected','deleted')),`source_type` text NOT NULL CHECK (`source_type` IN ('recipe','product','manual')),`source_name_snapshot` text DEFAULT '' NOT NULL,`recipe_id` text,`product_id` text,`recipe_calculation_id` text,`food_nutrition_record_id` text,`quantity` real CHECK (`quantity` IS NULL OR `quantity` > 0),`unit` text,`serving_count` real CHECK (`serving_count` IS NULL OR `serving_count` > 0),`portion_weight_grams` real CHECK (`portion_weight_grams` IS NULL OR `portion_weight_grams` > 0),`provenance_snapshot` text,`revision_reason` text DEFAULT '' NOT NULL,`supersedes_intake_revision_id` text,`created_by_principal_id` text NOT NULL,`created_at` integer NOT NULL,FOREIGN KEY (`nutrition_profile_id`) REFERENCES `nutrition_profiles`(`id`) ON DELETE restrict,FOREIGN KEY (`recipe_id`) REFERENCES `recipes`(`id`) ON DELETE restrict,FOREIGN KEY (`product_id`) REFERENCES `pantry_products`(`id`) ON DELETE restrict,FOREIGN KEY (`recipe_calculation_id`) REFERENCES `recipe_nutrition_calculations`(`id`) ON DELETE restrict,FOREIGN KEY (`food_nutrition_record_id`) REFERENCES `food_nutrition_records`(`id`) ON DELETE restrict,FOREIGN KEY (`supersedes_intake_revision_id`) REFERENCES `nutrition_intake_revisions`(`id`) ON DELETE restrict,FOREIGN KEY (`created_by_principal_id`) REFERENCES `nutrition_principals`(`id`) ON DELETE restrict,CHECK ((`state` IN ('eaten','corrected') AND `source_name_snapshot` <> '' AND `provenance_snapshot` IS NOT NULL) OR (`state` IN ('skipped','deleted') AND `provenance_snapshot` IS NULL)));
--> statement-breakpoint
CREATE UNIQUE INDEX `nutrition_intake_series_revision_idx` ON `nutrition_intake_revisions` (`series_id`,`revision`);
--> statement-breakpoint
CREATE INDEX `nutrition_intake_profile_occurred_idx` ON `nutrition_intake_revisions` (`nutrition_profile_id`,`occurred_at`);
--> statement-breakpoint
CREATE INDEX `nutrition_intake_recipe_idx` ON `nutrition_intake_revisions` (`recipe_id`);
--> statement-breakpoint
CREATE INDEX `nutrition_intake_product_idx` ON `nutrition_intake_revisions` (`product_id`);
--> statement-breakpoint
CREATE TABLE `nutrition_intake_nutrient_values` (`intake_revision_id` text NOT NULL,`nutrient_code` text NOT NULL,`amount` real NOT NULL CHECK (`amount` >= 0),`source_ids_snapshot` text NOT NULL,`confidence` real NOT NULL CHECK (`confidence` >= 0 AND `confidence` <= 1),`completeness` real NOT NULL CHECK (`completeness` >= 0 AND `completeness` <= 1),`estimated` integer NOT NULL CHECK (`estimated` IN (0,1)),PRIMARY KEY (`intake_revision_id`,`nutrient_code`),FOREIGN KEY (`intake_revision_id`) REFERENCES `nutrition_intake_revisions`(`id`) ON DELETE restrict,FOREIGN KEY (`nutrient_code`) REFERENCES `nutrient_definitions`(`code`) ON DELETE restrict);
--> statement-breakpoint
CREATE INDEX `nutrition_intake_nutrient_code_idx` ON `nutrition_intake_nutrient_values` (`nutrient_code`);
--> statement-breakpoint
CREATE TABLE `nutrition_meal_allocation_versions` (`id` text PRIMARY KEY NOT NULL,`series_id` text NOT NULL,`revision` integer NOT NULL CHECK (`revision` > 0),`nutrition_profile_id` text NOT NULL,`meal_plan_entry_id` text,`cook_session_id` text,`state` text NOT NULL CHECK (`state` IN ('planned','served','eaten','skipped','leftover')),`servings` real CHECK (`servings` IS NULL OR `servings` > 0),`portion_weight_grams` real CHECK (`portion_weight_grams` IS NULL OR `portion_weight_grams` > 0),`intake_series_id` text,`note` text DEFAULT '' NOT NULL,`supersedes_allocation_version_id` text,`created_by_principal_id` text NOT NULL,`created_at` integer NOT NULL,FOREIGN KEY (`nutrition_profile_id`) REFERENCES `nutrition_profiles`(`id`) ON DELETE restrict,FOREIGN KEY (`meal_plan_entry_id`) REFERENCES `meal_plan_entries`(`id`) ON DELETE restrict,FOREIGN KEY (`cook_session_id`) REFERENCES `cook_sessions`(`id`) ON DELETE restrict,FOREIGN KEY (`supersedes_allocation_version_id`) REFERENCES `nutrition_meal_allocation_versions`(`id`) ON DELETE restrict,FOREIGN KEY (`created_by_principal_id`) REFERENCES `nutrition_principals`(`id`) ON DELETE restrict,CHECK (`meal_plan_entry_id` IS NOT NULL OR `cook_session_id` IS NOT NULL),CHECK (`servings` IS NOT NULL OR `portion_weight_grams` IS NOT NULL),CHECK ((`state`='eaten' AND `intake_series_id` IS NOT NULL) OR (`state`<>'eaten' AND `intake_series_id` IS NULL)));
--> statement-breakpoint
CREATE UNIQUE INDEX `nutrition_allocation_series_revision_idx` ON `nutrition_meal_allocation_versions` (`series_id`,`revision`);
--> statement-breakpoint
CREATE INDEX `nutrition_allocation_profile_created_idx` ON `nutrition_meal_allocation_versions` (`nutrition_profile_id`,`created_at`);
--> statement-breakpoint
CREATE INDEX `nutrition_allocation_meal_plan_idx` ON `nutrition_meal_allocation_versions` (`meal_plan_entry_id`);
--> statement-breakpoint
CREATE INDEX `nutrition_allocation_cook_session_idx` ON `nutrition_meal_allocation_versions` (`cook_session_id`);
