import {
  Amphora,
  Apple,
  Banana,
  Bean,
  Beef,
  Beer,
  BeerOff,
  Blender,
  BottleWine,
  Cake,
  CakeSlice,
  Candy,
  CandyCane,
  Carrot,
  ChefHat,
  Cherry,
  Citrus,
  Coffee,
  ConciergeBell,
  Cookie,
  CookingPot,
  Croissant,
  CupSoda,
  Dessert,
  Donut,
  Drumstick,
  Egg,
  EggFried,
  Fish,
  FishSymbol,
  Flame,
  GlassWater,
  Grape,
  Ham,
  HandPlatter,
  IceCream,
  IceCreamBowl,
  IceCreamCone,
  Lollipop,
  Martini,
  Microwave,
  Milk,
  MilkOff,
  Nut,
  Pizza,
  Popcorn,
  Refrigerator,
  Salad,
  Sandwich,
  Shell,
  Shrimp,
  Soup,
  Sprout,
  Utensils,
  UtensilsCrossed,
  Vegan,
  Wheat,
  WheatOff,
  Wine,
  type LucideIcon,
} from 'lucide-react';

import { BordIcon } from '@/components/bord-brand';
import { DEFAULT_BRAND_ICON, type BrandIconId } from '@/lib/appearance';

export const BRAND_ICON_COMPONENTS = {
  'chef-hat': ChefHat,
  'cooking-pot': CookingPot,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  'hand-platter': HandPlatter,
  'concierge-bell': ConciergeBell,
  refrigerator: Refrigerator,
  microwave: Microwave,
  blender: Blender,
  flame: Flame,
  soup: Soup,
  salad: Salad,
  vegan: Vegan,
  sprout: Sprout,
  wheat: Wheat,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  citrus: Citrus,
  grape: Grape,
  carrot: Carrot,
  beef: Beef,
  drumstick: Drumstick,
  ham: Ham,
  fish: Fish,
  'fish-symbol': FishSymbol,
  egg: Egg,
  'egg-fried': EggFried,
  milk: Milk,
  sandwich: Sandwich,
  pizza: Pizza,
  nut: Nut,
  bean: Bean,
  shell: Shell,
  shrimp: Shrimp,
  cookie: Cookie,
  croissant: Croissant,
  donut: Donut,
  dessert: Dessert,
  cake: Cake,
  'cake-slice': CakeSlice,
  candy: Candy,
  'candy-cane': CandyCane,
  'ice-cream': IceCream,
  'ice-cream-bowl': IceCreamBowl,
  'ice-cream-cone': IceCreamCone,
  lollipop: Lollipop,
  popcorn: Popcorn,
  coffee: Coffee,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  martini: Martini,
  wine: Wine,
  beer: Beer,
  'bottle-wine': BottleWine,
  amphora: Amphora,
  'wheat-off': WheatOff,
  'milk-off': MilkOff,
  'beer-off': BeerOff,
} satisfies Record<Exclude<BrandIconId, 'table'>, LucideIcon>;

export function BrandIcon({
  icon = DEFAULT_BRAND_ICON,
  size = 24,
  strokeWidth = 2,
  className,
}: {
  icon?: BrandIconId;
  size?: number;
  strokeWidth?: number;
  className?: string;
}) {
  if (icon === 'table')
    return <BordIcon className={className} size={size} strokeWidth={strokeWidth} />;
  const Icon = BRAND_ICON_COMPONENTS[icon] ?? BRAND_ICON_COMPONENTS['chef-hat'];
  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} />;
}
